// <auto-generated />
using System;
using AspLab04.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspLab04.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("BookstoreMvc.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dale Carnegie",
                            BookCode = "BK-SKL-001",
                            GenreId = 1,
                            MinStock = 5,
                            Price = 88000m,
                            Publisher = "NXB Tổng hợp TP.HCM",
                            Quantity = 25,
                            Title = "Đắc Nhân Tâm"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Daniel Kahneman",
                            BookCode = "BK-SKL-002",
                            GenreId = 1,
                            MinStock = 5,
                            Price = 120000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 3,
                            Title = "Tư Duy Nhanh Và Chậm"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Paulo Coelho",
                            BookCode = "BK-NOV-001",
                            GenreId = 2,
                            MinStock = 3,
                            Price = 75000m,
                            Publisher = "NXB Hội Nhà Văn",
                            Quantity = 10,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            BookCode = "BK-NOV-002",
                            GenreId = 2,
                            MinStock = 3,
                            Price = 175000m,
                            Publisher = "NXB Tri Thức",
                            Quantity = 2,
                            Title = "Sapiens: Lược Sử Loài Người"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Stephen Hawking",
                            BookCode = "BK-SCI-001",
                            GenreId = 3,
                            MinStock = 3,
                            Price = 120000m,
                            Publisher = "NXB Trẻ",
                            Quantity = 0,
                            Title = "Lược Sử Thời Gian"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Robert C. Martin",
                            BookCode = "BK-TECH-001",
                            GenreId = 4,
                            MinStock = 3,
                            Price = 220000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 8,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 7,
                            Author = "David Thomas",
                            BookCode = "BK-TECH-002",
                            GenreId = 4,
                            MinStock = 3,
                            Price = 195000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 4,
                            Title = "The Pragmatic Programmer"
                        });
                });

            modelBuilder.Entity("BookstoreMvc.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Công nghệ"
                        });
                });

            modelBuilder.Entity("BookstoreMvc.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("BookstoreMvc.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("BookstoreMvc.Models.Book", b =>
                {
                    b.HasOne("BookstoreMvc.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookstoreMvc.Models.SaleItem", b =>
                {
                    b.HasOne("BookstoreMvc.Models.Book", "Book")
                        .WithMany("SaleItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreMvc.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BookstoreMvc.Models.Book", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("BookstoreMvc.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookstoreMvc.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}