// <auto-generated />
using System;
using AspLab04.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspLab04.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616154652_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AspLab04.Mvc.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            BookCode = "BK001",
                            GenreId = 1,
                            MinStock = 3,
                            Price = 250000m,
                            Publisher = "Prentice Hall",
                            Quantity = 10,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Andrew Hunt",
                            BookCode = "BK002",
                            GenreId = 1,
                            MinStock = 3,
                            Price = 280000m,
                            Publisher = "Addison Wesley",
                            Quantity = 8,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erich Gamma",
                            BookCode = "BK003",
                            GenreId = 1,
                            MinStock = 2,
                            Price = 350000m,
                            Publisher = "Addison Wesley",
                            Quantity = 5,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Stephen Hawking",
                            BookCode = "BK004",
                            GenreId = 2,
                            MinStock = 2,
                            Price = 180000m,
                            Publisher = "Bantam Books",
                            Quantity = 7,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Yuval Noah Harari",
                            BookCode = "BK005",
                            GenreId = 2,
                            MinStock = 2,
                            Price = 220000m,
                            Publisher = "Harper",
                            Quantity = 4,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.K. Rowling",
                            BookCode = "BK006",
                            GenreId = 3,
                            MinStock = 5,
                            Price = 200000m,
                            Publisher = "Bloomsbury",
                            Quantity = 15,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = 7,
                            Author = "James Clear",
                            BookCode = "BK007",
                            GenreId = 4,
                            MinStock = 3,
                            Price = 230000m,
                            Publisher = "Avery",
                            Quantity = 6,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Stephen Covey",
                            BookCode = "BK008",
                            GenreId = 4,
                            MinStock = 3,
                            Price = 210000m,
                            Publisher = "Free Press",
                            Quantity = 3,
                            Title = "The 7 Habits"
                        });
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Self Development"
                        });
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Book", b =>
                {
                    b.HasOne("AspLab04.Mvc.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.SaleItem", b =>
                {
                    b.HasOne("AspLab04.Mvc.Models.Book", "Book")
                        .WithMany("SaleItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspLab04.Mvc.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Book", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("AspLab04.Mvc.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
